import { NextApiRequest, NextApiResponse } from "next";

const employees = [
  {
    id: 1,
    firstName: "Brant",
    lastName: "Porkiss",
    email: "bporkiss0@whitehouse.gov",
    gender: "Male",
    imageUrl: "http://dummyimage.com/164x100.png/5fa2dd/ffffff",
  },
  {
    id: 2,
    firstName: "Clarita",
    lastName: "Edgecombe",
    email: "cedgecombe1@indiegogo.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/116x100.png/5fa2dd/ffffff",
  },
  {
    id: 3,
    firstName: "Jacquette",
    lastName: "Assiter",
    email: "jassiter2@slideshare.net",
    gender: "Female",
    imageUrl: "http://dummyimage.com/201x100.png/ff4444/ffffff",
  },
  {
    id: 4,
    firstName: "Vincenty",
    lastName: "Silbersak",
    email: "vsilbersak3@bing.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/189x100.png/5fa2dd/ffffff",
  },
  {
    id: 5,
    firstName: "Vaclav",
    lastName: "Menego",
    email: "vmenego4@state.tx.us",
    gender: "Male",
    imageUrl: "http://dummyimage.com/204x100.png/5fa2dd/ffffff",
  },
  {
    id: 6,
    firstName: "Auria",
    lastName: "MacSharry",
    email: "amacsharry5@icio.us",
    gender: "Female",
    imageUrl: "http://dummyimage.com/227x100.png/cc0000/ffffff",
  },
  {
    id: 7,
    firstName: "Gae",
    lastName: "Hallyburton",
    email: "ghallyburton6@moonfruit.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/207x100.png/cc0000/ffffff",
  },
  {
    id: 8,
    firstName: "Elbertine",
    lastName: "Bethell",
    email: "ebethell7@webs.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/190x100.png/dddddd/000000",
  },
  {
    id: 9,
    firstName: "Alis",
    lastName: "Boays",
    email: "aboays8@fema.gov",
    gender: "Female",
    imageUrl: "http://dummyimage.com/158x100.png/5fa2dd/ffffff",
  },
  {
    id: 10,
    firstName: "Eba",
    lastName: "Penhalewick",
    email: "epenhalewick9@japanpost.jp",
    gender: "Female",
    imageUrl: "http://dummyimage.com/208x100.png/cc0000/ffffff",
  },
  {
    id: 11,
    firstName: "Fair",
    lastName: "Pinchin",
    email: "fpinchina@shinystat.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/104x100.png/ff4444/ffffff",
  },
  {
    id: 12,
    firstName: "Grissel",
    lastName: "Glavias",
    email: "gglaviasb@de.vu",
    gender: "Female",
    imageUrl: "http://dummyimage.com/187x100.png/cc0000/ffffff",
  },
  {
    id: 13,
    firstName: "Haskell",
    lastName: "Hyndman",
    email: "hhyndmanc@ezinearticles.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/189x100.png/dddddd/000000",
  },
  {
    id: 14,
    firstName: "Wandie",
    lastName: "Mayall",
    email: "wmayalld@hao123.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/127x100.png/cc0000/ffffff",
  },
  {
    id: 15,
    firstName: "Yelena",
    lastName: "Sandilands",
    email: "ysandilandse@amazonaws.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/226x100.png/5fa2dd/ffffff",
  },
  {
    id: 16,
    firstName: "Frasier",
    lastName: "Krale",
    email: "fkralef@live.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/153x100.png/dddddd/000000",
  },
  {
    id: 17,
    firstName: "Romeo",
    lastName: "Dietsche",
    email: "rdietscheg@washingtonpost.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/189x100.png/cc0000/ffffff",
  },
  {
    id: 18,
    firstName: "Joly",
    lastName: "Arlt",
    email: "jarlth@bravesites.com",
    gender: "Polygender",
    imageUrl: "http://dummyimage.com/106x100.png/cc0000/ffffff",
  },
  {
    id: 19,
    firstName: "Orv",
    lastName: "Salmen",
    email: "osalmeni@stumbleupon.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/158x100.png/ff4444/ffffff",
  },
  {
    id: 20,
    firstName: "Gerrie",
    lastName: "Sansum",
    email: "gsansumj@theguardian.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/204x100.png/ff4444/ffffff",
  },
  {
    id: 21,
    firstName: "Ortensia",
    lastName: "Stonnell",
    email: "ostonnellk@printfriendly.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/156x100.png/cc0000/ffffff",
  },
  {
    id: 22,
    firstName: "Godfry",
    lastName: "Brimley",
    email: "gbrimleyl@devhub.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/210x100.png/ff4444/ffffff",
  },
  {
    id: 23,
    firstName: "Wallas",
    lastName: "Harrowell",
    email: "wharrowellm@1688.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/155x100.png/ff4444/ffffff",
  },
  {
    id: 24,
    firstName: "Minda",
    lastName: "Duckels",
    email: "mduckelsn@blinklist.com",
    gender: "Agender",
    imageUrl: "http://dummyimage.com/223x100.png/dddddd/000000",
  },
  {
    id: 25,
    firstName: "Dana",
    lastName: "Royal",
    email: "droyalo@washington.edu",
    gender: "Female",
    imageUrl: "http://dummyimage.com/190x100.png/dddddd/000000",
  },
  {
    id: 26,
    firstName: "Casey",
    lastName: "O'Doherty",
    email: "codohertyp@eventbrite.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/172x100.png/ff4444/ffffff",
  },
  {
    id: 27,
    firstName: "Biddie",
    lastName: "McGeffen",
    email: "bmcgeffenq@altervista.org",
    gender: "Female",
    imageUrl: "http://dummyimage.com/190x100.png/dddddd/000000",
  },
  {
    id: 28,
    firstName: "Annora",
    lastName: "Benediktovich",
    email: "abenediktovichr@plala.or.jp",
    gender: "Female",
    imageUrl: "http://dummyimage.com/171x100.png/5fa2dd/ffffff",
  },
  {
    id: 29,
    firstName: "Zaria",
    lastName: "Rainger",
    email: "zraingers@acquirethisname.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/157x100.png/ff4444/ffffff",
  },
  {
    id: 30,
    firstName: "Brodie",
    lastName: "Anglim",
    email: "banglimt@cnet.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/192x100.png/dddddd/000000",
  },
  {
    id: 31,
    firstName: "Patrizia",
    lastName: "Welbelove",
    email: "pwelbeloveu@delicious.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/170x100.png/ff4444/ffffff",
  },
  {
    id: 32,
    firstName: "Lek",
    lastName: "Jimeno",
    email: "ljimenov@biglobe.ne.jp",
    gender: "Male",
    imageUrl: "http://dummyimage.com/179x100.png/cc0000/ffffff",
  },
  {
    id: 33,
    firstName: "Goldina",
    lastName: "Barkas",
    email: "gbarkasw@google.com.hk",
    gender: "Female",
    imageUrl: "http://dummyimage.com/131x100.png/ff4444/ffffff",
  },
  {
    id: 34,
    firstName: "Parker",
    lastName: "Steffans",
    email: "psteffansx@cocolog-nifty.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/237x100.png/5fa2dd/ffffff",
  },
  {
    id: 35,
    firstName: "Gaylor",
    lastName: "Dinnage",
    email: "gdinnagey@shinystat.com",
    gender: "Bigender",
    imageUrl: "http://dummyimage.com/101x100.png/dddddd/000000",
  },
  {
    id: 36,
    firstName: "Cathleen",
    lastName: "Rampley",
    email: "crampleyz@taobao.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/115x100.png/5fa2dd/ffffff",
  },
  {
    id: 37,
    firstName: "Kania",
    lastName: "Richardes",
    email: "krichardes10@hp.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/237x100.png/ff4444/ffffff",
  },
  {
    id: 38,
    firstName: "Maire",
    lastName: "Jostan",
    email: "mjostan11@4shared.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/169x100.png/dddddd/000000",
  },
  {
    id: 39,
    firstName: "Arabelle",
    lastName: "Moncrefe",
    email: "amoncrefe12@123-reg.co.uk",
    gender: "Female",
    imageUrl: "http://dummyimage.com/211x100.png/ff4444/ffffff",
  },
  {
    id: 40,
    firstName: "Isabelle",
    lastName: "Pettigree",
    email: "ipettigree13@simplemachines.org",
    gender: "Female",
    imageUrl: "http://dummyimage.com/183x100.png/dddddd/000000",
  },
  {
    id: 41,
    firstName: "Rutherford",
    lastName: "Dudgeon",
    email: "rdudgeon14@imageshack.us",
    gender: "Male",
    imageUrl: "http://dummyimage.com/196x100.png/dddddd/000000",
  },
  {
    id: 42,
    firstName: "Jeno",
    lastName: "Bungey",
    email: "jbungey15@newsvine.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/102x100.png/dddddd/000000",
  },
  {
    id: 43,
    firstName: "Nata",
    lastName: "Tease",
    email: "ntease16@buzzfeed.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/144x100.png/cc0000/ffffff",
  },
  {
    id: 44,
    firstName: "Garey",
    lastName: "Greenhall",
    email: "ggreenhall17@ask.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/239x100.png/5fa2dd/ffffff",
  },
  {
    id: 45,
    firstName: "Aluino",
    lastName: "Feares",
    email: "afeares18@chron.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/147x100.png/5fa2dd/ffffff",
  },
  {
    id: 46,
    firstName: "Olav",
    lastName: "Pigney",
    email: "opigney19@buzzfeed.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/156x100.png/5fa2dd/ffffff",
  },
  {
    id: 47,
    firstName: "Harlene",
    lastName: "Crepin",
    email: "hcrepin1a@sun.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/200x100.png/dddddd/000000",
  },
  {
    id: 48,
    firstName: "Pris",
    lastName: "Jirek",
    email: "pjirek1b@geocities.jp",
    gender: "Female",
    imageUrl: "http://dummyimage.com/228x100.png/cc0000/ffffff",
  },
  {
    id: 49,
    firstName: "Charlie",
    lastName: "Kobieriecki",
    email: "ckobieriecki1c@meetup.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/226x100.png/5fa2dd/ffffff",
  },
  {
    id: 50,
    firstName: "Giovanni",
    lastName: "Tamburo",
    email: "gtamburo1d@comsenz.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/157x100.png/cc0000/ffffff",
  },
  {
    id: 51,
    firstName: "Joelly",
    lastName: "Humblestone",
    email: "jhumblestone1e@clickbank.net",
    gender: "Female",
    imageUrl: "http://dummyimage.com/159x100.png/ff4444/ffffff",
  },
  {
    id: 52,
    firstName: "Marv",
    lastName: "Duigan",
    email: "mduigan1f@netscape.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/222x100.png/5fa2dd/ffffff",
  },
  {
    id: 53,
    firstName: "Giulia",
    lastName: "Denham",
    email: "gdenham1g@php.net",
    gender: "Female",
    imageUrl: "http://dummyimage.com/140x100.png/dddddd/000000",
  },
  {
    id: 54,
    firstName: "Edie",
    lastName: "Clifforth",
    email: "eclifforth1h@weather.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/244x100.png/dddddd/000000",
  },
  {
    id: 55,
    firstName: "Nonnah",
    lastName: "Alentyev",
    email: "nalentyev1i@biblegateway.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/153x100.png/5fa2dd/ffffff",
  },
  {
    id: 56,
    firstName: "Betsy",
    lastName: "Trenholm",
    email: "btrenholm1j@ocn.ne.jp",
    gender: "Female",
    imageUrl: "http://dummyimage.com/236x100.png/5fa2dd/ffffff",
  },
  {
    id: 57,
    firstName: "Alfie",
    lastName: "Bartod",
    email: "abartod1k@cyberchimps.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/243x100.png/cc0000/ffffff",
  },
  {
    id: 58,
    firstName: "Fayre",
    lastName: "Ratcliffe",
    email: "fratcliffe1l@cloudflare.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/166x100.png/5fa2dd/ffffff",
  },
  {
    id: 59,
    firstName: "Andy",
    lastName: "Rosander",
    email: "arosander1m@meetup.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/164x100.png/dddddd/000000",
  },
  {
    id: 60,
    firstName: "Malissia",
    lastName: "McParlin",
    email: "mmcparlin1n@netlog.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/189x100.png/cc0000/ffffff",
  },
  {
    id: 61,
    firstName: "Griffith",
    lastName: "Conman",
    email: "gconman1o@photobucket.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/176x100.png/ff4444/ffffff",
  },
  {
    id: 62,
    firstName: "Camille",
    lastName: "Marrington",
    email: "cmarrington1p@bloglovin.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/169x100.png/cc0000/ffffff",
  },
  {
    id: 63,
    firstName: "Reeva",
    lastName: "Cockshtt",
    email: "rcockshtt1q@dot.gov",
    gender: "Female",
    imageUrl: "http://dummyimage.com/180x100.png/dddddd/000000",
  },
  {
    id: 64,
    firstName: "Elysee",
    lastName: "Lisimore",
    email: "elisimore1r@home.pl",
    gender: "Female",
    imageUrl: "http://dummyimage.com/116x100.png/ff4444/ffffff",
  },
  {
    id: 65,
    firstName: "Alvie",
    lastName: "Smallman",
    email: "asmallman1s@sourceforge.net",
    gender: "Male",
    imageUrl: "http://dummyimage.com/119x100.png/dddddd/000000",
  },
  {
    id: 66,
    firstName: "Martie",
    lastName: "Hacaud",
    email: "mhacaud1t@amazon.co.jp",
    gender: "Female",
    imageUrl: "http://dummyimage.com/141x100.png/ff4444/ffffff",
  },
  {
    id: 67,
    firstName: "Gina",
    lastName: "Hellyar",
    email: "ghellyar1u@adobe.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/179x100.png/dddddd/000000",
  },
  {
    id: 68,
    firstName: "Lanna",
    lastName: "Zamora",
    email: "lzamora1v@wikia.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/199x100.png/cc0000/ffffff",
  },
  {
    id: 69,
    firstName: "Nance",
    lastName: "Stenners",
    email: "nstenners1w@youku.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/206x100.png/ff4444/ffffff",
  },
  {
    id: 70,
    firstName: "Ware",
    lastName: "Shiers",
    email: "wshiers1x@unesco.org",
    gender: "Male",
    imageUrl: "http://dummyimage.com/155x100.png/dddddd/000000",
  },
  {
    id: 71,
    firstName: "Otho",
    lastName: "Minifie",
    email: "ominifie1y@t-online.de",
    gender: "Male",
    imageUrl: "http://dummyimage.com/222x100.png/ff4444/ffffff",
  },
  {
    id: 72,
    firstName: "Artemas",
    lastName: "Olyunin",
    email: "aolyunin1z@pbs.org",
    gender: "Male",
    imageUrl: "http://dummyimage.com/198x100.png/5fa2dd/ffffff",
  },
  {
    id: 73,
    firstName: "Edin",
    lastName: "Dachs",
    email: "edachs20@lycos.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/147x100.png/dddddd/000000",
  },
  {
    id: 74,
    firstName: "Nolie",
    lastName: "Buntin",
    email: "nbuntin21@techcrunch.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/155x100.png/cc0000/ffffff",
  },
  {
    id: 75,
    firstName: "Daisey",
    lastName: "Frane",
    email: "dfrane22@go.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/234x100.png/dddddd/000000",
  },
  {
    id: 76,
    firstName: "Sher",
    lastName: "Cawthera",
    email: "scawthera23@house.gov",
    gender: "Female",
    imageUrl: "http://dummyimage.com/130x100.png/cc0000/ffffff",
  },
  {
    id: 77,
    firstName: "Berte",
    lastName: "Tilio",
    email: "btilio24@gravatar.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/118x100.png/cc0000/ffffff",
  },
  {
    id: 78,
    firstName: "Dannel",
    lastName: "Meletti",
    email: "dmeletti25@senate.gov",
    gender: "Male",
    imageUrl: "http://dummyimage.com/178x100.png/ff4444/ffffff",
  },
  {
    id: 79,
    firstName: "Maye",
    lastName: "Forrest",
    email: "mforrest26@whitehouse.gov",
    gender: "Female",
    imageUrl: "http://dummyimage.com/198x100.png/5fa2dd/ffffff",
  },
  {
    id: 80,
    firstName: "Debbie",
    lastName: "Hubback",
    email: "dhubback27@webnode.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/250x100.png/5fa2dd/ffffff",
  },
  {
    id: 81,
    firstName: "Fran",
    lastName: "Charleston",
    email: "fcharleston28@godaddy.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/110x100.png/ff4444/ffffff",
  },
  {
    id: 82,
    firstName: "Georgine",
    lastName: "MacParlan",
    email: "gmacparlan29@bigcartel.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/207x100.png/5fa2dd/ffffff",
  },
  {
    id: 83,
    firstName: "Aloysia",
    lastName: "Kinchin",
    email: "akinchin2a@skyrock.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/110x100.png/cc0000/ffffff",
  },
  {
    id: 84,
    firstName: "Germaine",
    lastName: "Behninck",
    email: "gbehninck2b@discuz.net",
    gender: "Female",
    imageUrl: "http://dummyimage.com/120x100.png/dddddd/000000",
  },
  {
    id: 85,
    firstName: "Dolli",
    lastName: "Getsham",
    email: "dgetsham2c@cloudflare.com",
    gender: "Bigender",
    imageUrl: "http://dummyimage.com/170x100.png/dddddd/000000",
  },
  {
    id: 86,
    firstName: "Gareth",
    lastName: "Obal",
    email: "gobal2d@tmall.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/208x100.png/dddddd/000000",
  },
  {
    id: 87,
    firstName: "Loree",
    lastName: "Alston",
    email: "lalston2e@discuz.net",
    gender: "Genderqueer",
    imageUrl: "http://dummyimage.com/197x100.png/cc0000/ffffff",
  },
  {
    id: 88,
    firstName: "Griffie",
    lastName: "Emery",
    email: "gemery2f@pbs.org",
    gender: "Male",
    imageUrl: "http://dummyimage.com/227x100.png/5fa2dd/ffffff",
  },
  {
    id: 89,
    firstName: "Tad",
    lastName: "Wortman",
    email: "twortman2g@desdev.cn",
    gender: "Male",
    imageUrl: "http://dummyimage.com/147x100.png/dddddd/000000",
  },
  {
    id: 90,
    firstName: "Lane",
    lastName: "Arendsen",
    email: "larendsen2h@ebay.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/232x100.png/cc0000/ffffff",
  },
  {
    id: 91,
    firstName: "Gregor",
    lastName: "Toppes",
    email: "gtoppes2i@artisteer.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/146x100.png/ff4444/ffffff",
  },
  {
    id: 92,
    firstName: "Sheba",
    lastName: "Bywaters",
    email: "sbywaters2j@adobe.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/100x100.png/5fa2dd/ffffff",
  },
  {
    id: 93,
    firstName: "Bald",
    lastName: "Church",
    email: "bchurch2k@i2i.jp",
    gender: "Male",
    imageUrl: "http://dummyimage.com/101x100.png/cc0000/ffffff",
  },
  {
    id: 94,
    firstName: "Caddric",
    lastName: "Kerrey",
    email: "ckerrey2l@lycos.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/168x100.png/5fa2dd/ffffff",
  },
  {
    id: 95,
    firstName: "Dynah",
    lastName: "Cristoforetti",
    email: "dcristoforetti2m@list-manage.com",
    gender: "Female",
    imageUrl: "http://dummyimage.com/172x100.png/5fa2dd/ffffff",
  },
  {
    id: 96,
    firstName: "Chane",
    lastName: "Semper",
    email: "csemper2n@gmpg.org",
    gender: "Male",
    imageUrl: "http://dummyimage.com/131x100.png/dddddd/000000",
  },
  {
    id: 97,
    firstName: "Symon",
    lastName: "Collocott",
    email: "scollocott2o@ebay.com",
    gender: "Male",
    imageUrl: "http://dummyimage.com/176x100.png/5fa2dd/ffffff",
  },
  {
    id: 98,
    firstName: "Kassandra",
    lastName: "Domnick",
    email: "kdomnick2p@china.com.cn",
    gender: "Female",
    imageUrl: "http://dummyimage.com/171x100.png/5fa2dd/ffffff",
  },
  {
    id: 99,
    firstName: "Andeee",
    lastName: "Shillaker",
    email: "ashillaker2q@ca.gov",
    gender: "Female",
    imageUrl: "http://dummyimage.com/188x100.png/cc0000/ffffff",
  },
  {
    id: 100,
    firstName: "Paquito",
    lastName: "Raffels",
    email: "praffels2r@unblog.fr",
    gender: "Male",
    imageUrl: "http://dummyimage.com/121x100.png/dddddd/000000",
  },
];

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  return res.status(200).json(employees);
}
